apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: odoo
spec:
  storageClassName: # standard-rwo # standard-rwo is default - so its possible that we dont need to pass its name - test it !! 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
