apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-app-deployment
  namespace: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-app-deployment
template:
  metadata:
    labels:
      app: odoo-app-deployment
  spec:
    containers:
    - name: odoo-app
      image: docker.io/bitnami/odoo:16
      ports:
      - containerPort: 8069
      env:
      # service name like docker compose network and container name ?  
      - name: ODOO_DATABASE_HOST
        value: "postgresql-svc.odoo.svc.cluster.local"
      - name: ODOO_DATABASE_PORT_NUMBER
        value: "5432"
      - name: ODOO_DATABASE_NAME
        value: "bitnami_odoo"
      - name: ODOO_DATABASE_USER
        value: "bn_odoo"
      - name: ODOO_DATABASE_PASSWORD
        value: "mypassword"
      - name: ODOO_EMAIL
        value: "user@example.com"
      - name: ODOO_PASSWORD
        value: "bitnami"
      volumeMounts:
      - name: odoo-data
        mountPath: /bitnami/odoo
    volumes:
    - name: odoo-data
      emptyDir: {}
